version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: my-app-backend
    restart: unless-stopped
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app 
    networks:
      - app-network
    depends_on:
      - mongo 
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONOGODB_URI=${MONOGODB_URI}
      - DB_NAME=${DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}


  # Frontend Service 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Build-time arguments must be placed inside the 'build' block.
      args:
        - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
    container_name: my-app-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: my-app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local