
version: '3.7'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
    # EB ignores the host port mapping, but this is useful for local testing.
    # The container will expose port 8000.
    expose:
      - '8000'
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONOGODB_URI=${MONOGODB_URI}
      - DB_NAME=${DB_NAME}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}

  # React Frontend + Nginx Proxy Service
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_PREFIX=${VITE_BACKEND_PREFIX}
    ports:
      - '80:80'
    depends_on:
      - backend