
version: '3.7'

services:
  # FastAPI Backend Service
  backend:
    image: 914261933179.dkr.ecr.us-west-2.amazonaws.com/backend:latest
    expose:
      - '8000'
    environment:
      - DB_NAME=${DB_NAME}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}

  # React Frontend + Nginx Proxy Service
  frontend:
    image: 914261933179.dkr.ecr.us-west-2.amazonaws.com/frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend